HC-IPPM/safe-inputs

- Makefile
Flux doesn't like `flux-credentials` anymore I guess.
> Use correct flux secret name

- ui/cloudbuild.yaml
The dockerfile already builds the production bundle, so this can be removed to speed up the deployments.
> remove redundant build step

- api/kubernetes/deployment.yaml
This commit fixes the `Deployment/api/api validation error: cannot restore slice from map` error we were seeing in the flux logs by [passing the secretRef as an array](https://opensource.com/article/19/6/introduction-kubernetes-secrets-and-configmaps#:~:text=envFrom%3A%0A%0A%2D%20secretRef%3A%0A%0A%C2%A0%20%C2%A0%20name%3A%20mariadb%2Duser%2Dcreds).
> pass array to secretRef

- ui/src/setupTests.js
This commit mocks the react-i18next library to resolve the warning that appears when we run the tests:
```js
console.warn
react-i18next:: You will need to pass in an i18next instance by using initReactI18next
137 |     undefined
138 |
> 139 |   const { t } = useTranslation()
|                 ^
140 |
141 |   //
142 |   // Function for the API call -> useMutation
```
A solution (the one I went with) is to mock the `t` function to return whatever is passed, so that translations don't need to be loaded in tests. This mock is applied once per test file using the `setupTests.js` file that jest's config option [setupfilesafterenv](https://jestjs.io/docs/configuration#setupfilesafterenv-array) is pointing to.
> Mock react-i18next to fix warning

- api/index.js
- api/package-lock.json
- api/package.json
- api/src/Server.js
- api/src/__tests__/Server.test.js
- ui/src/index.tsx
Removed excess dependencies, fixed tests to work with graphql-yoga 3, changed pluggins to limit complexity as graphql-armor was no longer compatible with the new version of graphql-yoga.
> Update graphql yoga

- ui/package.json
Jest (the testing framework used by default with Create React App) has an option to report on how many lines of code are covered by tests. This commit enables that option.
> Enable test coverage reporting for the UI

- ui/package-lock.json
- ui/package.json
- ui/src/components/Link.tsx
- ui/src/components/RouterLink.tsx
- ui/src/components/auth/AuthNavButton.tsx
- ui/src/components/layout/Footer.tsx
- ui/src/components/layout/Header.tsx
- ui/src/index.tsx
- ui/src/pages/TermsAndConditions.tsx
Two components:
- increase consistency in use of react router links vs raw anchors (via Chakra). Header links to the homepage no longer cause a full app reload/session re-sync
- add [spin-delay](https://www.npmjs.com/package/spin-delay) to the `AuthNavButton`, to avoid flashing short lived loading states on session syncs
> Reduce auth nav button spinner flashes

- ui/.eslintrc
- ui/rspack.config.js
- ui/src/components/DataTable.tsx
- ui/src/components/TableCell.tsx
- ui/src/components/auth/AuthNavButton.tsx
- ui/src/components/layout/Footer.tsx
- ui/src/components/layout/Header.tsx
- ui/src/pages/ExcelParser.tsx
- ui/src/pages/NavPage.tsx
- ui/src/pages/NavWrapper.tsx
- ui/src/pages/SignIn.tsx
- ui/src/pages/TermsAndConditions.tsx
- ui/tsconfig.json
Helps keep module imports sane, especially when directory refactoring happens. Not specifically planning any big refactors soon, but I wanted to set this up before I forgot.
Will apply the same rules in the api dir after porting it to TS, which I plan to do soon.
> Restrict relative imports to sibling/child modules in the ui directory

- api/Dockerfile.prod
- api/cloudbuild.yaml
- api/package.json
The TS compilation step in the previous `api/Dockerfile.prod` file was failing, the `api/tsconfig.json` was not properly configured for it (set `noEmit: true` for one thing :facepalm: haha). On further reading, I decided it wasn't worth the headache and pain points of either a) additional dependencies (pick your bundler) and configuration management to properly build our current source for a plain node run time, or b) writing source with idiosyncratic patterns (maybe require statments, probably lying to source and using `.js` in module paths even when actually targeting `.ts` modules...) and diverging from the patterns used on the `/ui` side.
The `tsx` maintainers have left the question of whether it's fit for production [as an exercise for the …
> In prod, run the api via tsx, rather than trying to compile for and run in node

- kubernetes/apps/gke/api/authzpol.yaml
Allow ingress from ingressgateway pod to api.
> feat: allow ingress to api authz policy

- api/src/__tests__/authz.test.ts
- api/src/__tests__/error_utils.test.ts
- api/src/create_app.ts
- api/src/env.ts
- api/src/error_utils.ts
Replace the default express.js error handling behaviour of returning an HTML response containing the error message with a custom handler that returns the error message in JSON for the client side app to catch and choose how to display.
Will be opening follow up issues for related next steps.
> API error handling

- renovate.json5
As discussed in https://github.com/PHACDataHub/safe-inputs/pull/187#pullrequestreview-2148292813.
> feat: ignore pinning for flux managed images

- ui/src/components/Link.tsx
Addresses the following warning:
```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
Check the render method of `Styled(button)`.
at Link (http://localhost:8080/main.js:19362:19)
at http://localhost:8080/main.js:4530:71
at ChakraComponent (http://localhost:8080/main.js:119447:107)
at http://localhost:8080/main.js:114247:87
at AuthNavButton (http://localhost:8080/main.js:19444:96)
...
```
Also tightens up the function overload types slightly, the external link case shouldn't use the `to` prop.
> Fix Link ref passing

- api/src/create_app.ts
- ui/src/components/auth/auth_utils.ts
- ui/src/index.tsx
Configure the Apollo client to get and include a CSRF token in all requests. Configure GraphiQL to use GET requests (which don't require CSRF) for queries. Note: mutations written in GraphiQL will still be blocked by CSRF/auth checks, but I think that's a feature not a bug.
> Fix CSRF on GQL queries

- .eslintrc
- .prettierrc
- api/.eslintrc
- api/package-lock.json
- api/package.json
- package-lock.json
- package.json
- ui/.eslintrc
- ui/package-lock.json
- ui/package.json
Add additional eslint security plugins:
- [Microsoft's SDL/SAST plugins](https://www.npmjs.com/package/@microsoft/eslint-plugin-sdl), for assorted common and environment specific (node in the api and react in the ui) rules
- [`eslint-plugin-security`](https://www.npmjs.com/package/eslint-plugin-security) for additional node-specific coverage on in the api
- [`eslint-plugin-no-secrets`](https://www.npmjs.com/package/eslint-plugin-no-secrets) for secret detection (in ts/js only, redundant to GitHub secret push prevention, but defense in depth/live linter hints can't hurt)
I considered a few other plugins but haven't put them aside for now. These two in particular are promising for further consideration, pending continued signs of life from their repos:
- …
> Eslint security plugins

- kubernetes/apps/base/api/mongodb.yaml
Closes #240 
Relevant docs: https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/logging.md.
Assuming the kubernetes operator follows the official mongo conventions, the default log level should be set to `INFO`. [Here's](https://www.mongodb.com/docs/ops-manager/current/reference/mongodb-agent-settings/#mongodb-setting-logLevel) a list of valid values.
> feat: update mongo agent log file to stdout

- api/jest.config.cjs
- ui/babel.config.cjs
- ui/jest.config.cjs
- ui/package-lock.json
- ui/package.json
- ui/rspack.config.cjs
- ui/src/components/LanguageButton.test.tsx
- ui/src/test_utils/TestProviders.tsx
- ui/src/test_utils/mocks/styleMock.js
- ui/src/test_utils/mocks/svgMock.js
- ui/test/LanguageButton.test.tsx
Lingui's `macro` babel plugin can't handle the output of TypeScript's JSX transpiler. Our babel configuration, previously inside of `rspack.config.cjs`, worked because [plugins are run before any presets](https://babeljs.io/docs/plugins#plugin-ordering). Our Jest configuration did not, because my choice to try using `ts-jest`, for consistency with the `/api` jest configuration, meant that TypeScript was being run first (because our babel configuration was embedded in our rspack config, it wasn't picking up our babel config at all either way).
Ultimately, the `/ui` jest doesn't need to be using `ts-jest`, and the jest environment is closer to the real runtime if it just uses babel, sharing the runtime configuration.
Aside from that and some related misc jest configuration tweaks, I moved …
> UI Jest/Lingui compatibility fix, and related test utilities

- kubernetes/clusters/gke/components.yaml
- kubernetes/components/configs/capacitor.yaml
- kubernetes/components/configs/certificate.yaml
- kubernetes/components/configs/gateway.yaml
- Split dev and prod subdomain gateway and certificates
- Move capacitor to dev i.e, https://capacitor.dev.safeinputs.alpha.phac-aspc.gc.ca/
This would make it easier to address https://github.com/PHACDataHub/safe-inputs/issues/475 as we can add OAuth for all `*.dev` subdomains which could host internal dashboards.
> Split dev subdomain and move capacitor

- kubernetes/components/controllers/capacitor.yaml
Reverts PHACDataHub/safe-inputs#465
Adding digest on a tag causes errors during reconciliation as (_I'm guessing_) there's no such tag called `v0.4.2@sha256:1e72940be8383cd5054e3efcff8ec36f27e33959a4b940fc4b956c932083578b` in the [capacitor registry](https://github.com/gimlet-io/capacitor/pkgs/container/capacitor-manifests).
<details>
<summary>Error message</summary>
```sh
> kubectl events --for OCIRepository/capacitor -n capacitor
LAST SEEN            TYPE      REASON                  OBJECT                    MESSAGE
24s (x30 over 18h)   Warning   OCIArtifactPullFailed   OCIRepository/capacitor   failed to determine artifact digest: GET https://github.com/-/v2/packages/container/package/gimlet-io%!F(MISSING)capacitor-manifests%!F(MISSING)manifests%!F(MISSING)v0.4.2: unexpected status …
```
> Revert "chore: pin ghcr.io/gimlet-io/capacitor-manifests docker tag to 1e72940"

- renovate.json5
Relates to https://github.com/PHACDataHub/safe-inputs/pull/505#issue-2478144189
In case anyone's wondering why, unlike [here](https://github.com/PHACDataHub/safe-inputs/blob/8207575174f87313cd4c212e5a7b76a9223e7b20/renovate.json5#L27-L29), I used `pinDigests` (plural) instead of `pinDigest` - Although setting `pinDigest` ignores any PR's related to digest updates, it doesn't really stop a digest from creeping in via a `patch` update type.
> feat: ignore pinning for capacitor OCI repository

- kubernetes/clusters/gke/flux-podmonitor.yaml
Set up [managed prometheus metric collection](https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-managed) for Flux pods.
> feat: add pod monitor for Flux pods

- api/package-lock.json
- api/package.json
Renovate's package-lock editing was creating inconsistencies between mongoose's specific mongodb version requirements and the redundant direct mongodb dependency declared in `api/package.json` This was the problem with #222.
> Remove redundant mongodb dependency in api/package.json

- api/src/authn.ts
- api/src/types/Express.d.ts
Promised follow up to hotfix d370e847d1df1f5c3b59651bef26cb9ea5df3b41, fixing an older outstanding typing mistake I'd made as well as the hacky portion of that hotfix.
> Correct the Request type consumed in api/src/authn.ts, remove redundant properties added to Express.Request

- devsecops/artifact-registry-vulnerability-scanning/cli-deployment-reference/README.md
The devsecops/artifact-registry-vulnerability-scanning/cloudbuild deploys the vulnerability filtering cloud function.  Now that we have the trigger set up https://github.com/PHACDataHub/acm-core/pull/402, this PR is making a minor change to this directory in order to trigger the initial deployment of the function (with push to main).
> fix: launch cloud function now that cloudbuild trigger is enabled

- devsecops/artifact-registry-vulnerability-scanning/cli-deployment-reference/README.md
- devsecops/artifact-registry-vulnerability-scanning/cli-deployment-reference/init.sh
- devsecops/artifact-registry-vulnerability-scanning/cloudbuild.yaml
When triggering the cloudbuild for the cloud function locally, I found I needed to supply substitutions for variables (had done this with the cli command), and unless they were prefixed by '_' it would produce an error.   Unfortunately, when using the cloudbuild trigger, _BRANCH_NAME isn't a built in substitution so the function never deployed when it had actually merged with main as $BRANCH_NAME == 'main', not $_BRANCH_NAME == 'main' as it was written in the function. 
When fixing this, I also noticed I wasn't providing the bucket name or service account substitutions for this when using the cloud build trigger. 
In this PR, the instructions to deploy function with cloudbuild locally were removed, and in cloudbuild.yaml, added the missing substitutions and changed the built in ones to …
> fix: cloud function cloudbuild substitutions

- devsecops/axe-testing/cloudbuild.yaml
Will hopefully resolve:
"Your build failed to run: generic::invalid_argument: if 'build.service_account' is specified, the build must either (a) specify 'build.logs_bucket', (b) use the REGIONAL_USER_OWNED_BUCKET build.options.default_logs_bucket_behavior option, or (c) use either CLOUD_LOGGING_ONLY / NONE logging options"
> fix: added default logs bucket behaviour to axe-testing cloudbuild.yaml

- devsecops/artifact-registry-vulnerability-scanning/README.md
- devsecops/artifact-registry-vulnerability-scanning/cli-deployment-reference/init.sh
- devsecops/artifact-registry-vulnerability-scanning/cloud-function/package-lock.json
- package.json
The original intent was to make minor rewording changes in the README / init.sh in order to re-trigger the cloudbuild initial deployment of the cloud function as it failed due to missing permissions last time and have since [added the missing cloud function service agent role](https://github.com/PHACDataHub/acm-core/pull/407).
However, there was a renovate fix push to main branch in the meantime, which triggered the cloudbuild, and it [still failed due to missing permissions ](https://console.cloud.google.com/cloud-build/builds;region=northamerica-northeast1/f6827dad-b9d3-4f55-9807-f3872571e3dc?cloudshell=true&inv=1&invt=AbjPmw&project=phx-01j1tbke0ax).
Have added more permissions: https://github.com/PHACDataHub/acm-core/pull/409, and trying this again. 
(It's probably poor form to do …
> fix: deploy vuln cloud function - and include in main cloudbuild ci:all command

- devsecops/artifact-registry-vulnerability-scanning/cli-deployment-reference/init.sh
- devsecops/artifact-registry-vulnerability-scanning/cloudbuild.yaml
Added the --build-service-account line to cloudbuild.yaml to use the custom cloudbuild service account (that has the service account user on the cloud function). (suggestion from https://github.com/PHACDataHub/acm-core/pull/414, https://cloud.google.com/functions/docs/reference/iam/roles#additional-configuration) . Also made a minor change to init.sh (added the word 'an' to a comment with the intention of triggering cloudbuild deployment of the function, but now we have an actual change to do that.)
> fix: trigger cloud function deployment - added custom build service account tag in cloud build. 

- devsecops/artifact-registry-vulnerability-scanning/cloudbuild.yaml
The last PR (https://github.com/HC-IPPM/safe-inputs/pull/1033) failed (https://console.cloud.google.com/cloud-build/builds;region=northamerica-northeast1/bacfca1c-40f3-4230-a271-91d0817863fc?project=phx-01j1tbke0ax).  
I double checked the the permissions, and the cloudbuild service account looks like it has the act as on the cloud function service account.  The error message looks like the PROJECT_ID built in cloudbuild substitution wasn't working correctly as it's just a dash in the error message.  
Added in brackets around the cloudbuild variables to see if this will resolve error and pick up PROJECT_ID (next will try hard coding). 
(Also added an '=' in the --service-account line to be consistent)
> fix: wrapped project_id in brackets in cloudbuild

- api/cloudbuild.yaml
- api/docker-compose.dev-test.yaml
- api/package.json
- devsecops/axe-testing/Dockerfile
- devsecops/axe-testing/cloudbuild.yaml
- devsecops/axe-testing/package.json
- ui/cloudbuild.yaml
- ui/jest.config.cjs
- ui/package.json
Collects and saves test coverage reports with the _ui_, _api_ and _axe-testing_ cloudbuild.yamls. 
If there's a previous commit on the current branch, it extracts the previous commits code coverage percentage (statements) and appends the difference to the report file (to see if coverage is trending up or down). 
This doesn't yet involve README badges nor does it make use of a threshold to fail.  Just informational at the moment.
> feat: initial test coverage reporting (saving to bucket)

- renovate.json5
Due to reason mentioned [here](https://github.com/HC-IPPM/safe-inputs/pull/655#issuecomment-2377463287).
> feat: ignore docker updates for flux images

- api/cloudbuild.yaml
- devsecops/artifact-registry-vulnerability-scanning/cloudbuild.yaml
- ui/cloudbuild.yaml
This is a workaround in order to easily (for now) filter current image vulnerabilities in the dashboard. 
Added as a final step in the ui, api, and cloud function cloudbuild.yamls.  Also re-added the if main conditional around the function that was removed when troubleshooting service accounts.
> feat: save commit sha to bucket when images are pushed 

- api/cloudbuild.yaml
- devsecops/artifact-registry-vulnerability-scanning/cloudbuild.yaml
- ui/cloudbuild.yaml
gsuitl wasn't found in the base image for cloudbuild (https://console.cloud.google.com/cloud-build/builds;region=northamerica-northeast1/2c3143c4-9345-4dd1-bab8-57ca4bfb227a?invt=Abo8dw&project=phx-01j1tbke0ax), so swapped it for the cloud-sdk image.  This is a continuation/ fix of https://github.com/HC-IPPM/safe-inputs/pull/1131 (as the cloudbuilds for that PR failed on main branch).
> fix: changed base image of the get-and-save-artifact-registry-image-digest-if-main cloudbuild steps 
